SSHOTCP-7293 Create the default role in CSM for Fabric Manager RBAC
Cray-HPE/keycloak-installer pull request #61
Opened 2024-07-11 01:41 UTC by sehan-snyk

## Summary and Scope

The PR is about creating the default service account `slingshot-admin-client` and its role as `slingshot-admin` during the CSM installation.

This will be backward compatible since new service account and role will be created on top of the existing roles. 

Slingshot FM NB API has been used `admin-client`. Once the CSM 1.6 is out then Slingshot FM shall be adjusted to use `slingshot-admin-client` instead of CSM `admin-client`. 

## Issues and Related PRs

_List and characterize relationship to Jira/Github issues and other pull requests. Be sure to list dependencies._

* Resolves [issue id](issue link)
* Change will also be needed in `<insert branch name here>`
* Future work required by [issue id](issue link)
* Documentation changes required in [issue id](issue link)
* Merge with/before/after `<insert PR URL here>`

## Testing

TBD

### Tested on:

  * `<development system>`
  * Local development environment
  * Virtual Shasta

### Test description:

_How were the changes tested and success verified? If schema changes were part of this change, how were those handled in your upgrade/downgrade testing?_

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)?
- Were continuous integration tests run? If not, why?
- Was upgrade tested? If not, why?
- Was downgrade tested? If not, why?
- Were new tests (or test issues/Jiras) created for this change?

## Risks and Mitigations

_Are there known issues with these changes? Any other special considerations?_

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

2024-07-18 18:39 UTC, ndavidson-hpe requested changes
There should also be tests added for this client like the ones that were deleted from the admin client.

2024-07-25 21:25 UTC, ndavidson-hpe requested changes

2024-07-25 21:25 UTC, ndavidson-hpe commented on kubernetes/cray-keycloak/templates/keycloak-setup.yaml
> +            {{ .Values.setup.keycloak.systemNexusClient.secret.namespaces | toJson }}
```suggestion
            {{ .Values.setup.keycloak.systemSlingshotClient.secret.namespaces | toJson }}
```

2024-07-25 21:42 UTC, ndavidson-hpe approved these changes

2024-07-26 16:23 UTC, atifsyedali approved these changes

2024-07-26 17:18 UTC, kimjensen-hpe approved these changes

2024-07-26 17:19 UTC, merged